/*
 * SUPERSEDED — the gallery is a tiled collage now, not a scattered pile.
 *
 * Nothing in the shipping stylesheet comes from this file any more; the
 * layout is generated by gen-collage.mjs and verified by check-collage.mjs.
 * Kept because it is the rollback path: it is the only record of how the
 * scattered pile was built, and rebuilding that by hand would be a day's
 * work over eighteen positions.
 *
 * If the collage is here to stay, delete this, scatter-layout.mjs and
 * check-scatter.mjs together — they only make sense as a set.
 */
/*
 * Verifies a print-pile layout against the two rules in globals.css.
 *
 * RULE ONE  no print may spill far outside the stage.
 * RULE TWO  no print's CENTRE may fall underneath a print stacked above it,
 *           or that photograph is unopenable while looking perfectly fine.
 *
 * Rule two is checked against the ROTATED rectangle, not the axis-aligned
 * one: every print is turned a few degrees, and the naive check is optimistic
 * for a rotated box. The centre of the lower print is transformed into the
 * upper print's local frame and tested against its half-extents.
 *
 * A print is 1.08x as tall as it is wide (square photo, thin sides, deep
 * chin). Its width is a % of the STAGE WIDTH, so as a fraction of stage
 * HEIGHT its height is 1.08 * w * aspect.
 *
 *     node scripts/check-scatter.mjs
 */

const TALL = 1.08;

function halfExtents(w, aspect) {
  return { hw: w / 2, hh: (TALL * w * aspect) / 2 };
}

/* Is `pt` (in stage %) inside `box` after undoing box's rotation? */
function covers(box, pt, aspect) {
  const { hw, hh } = halfExtents(box.w, aspect);
  const rad = (-(box.rot || 0) * Math.PI) / 180;
  /* Into the box's local frame. x is in stage-width %, y in stage-height %,
     so both are converted to a common unit (stage width %) before rotating,
     then back — otherwise the rotation is sheared by the aspect. */
  const dx = pt.x - box.x;
  const dy = (pt.y - box.y) / aspect;
  const lx = dx * Math.cos(rad) - dy * Math.sin(rad);
  const ly = dx * Math.sin(rad) + dy * Math.cos(rad);
  return Math.abs(lx) < hw && Math.abs(ly * aspect) < hh;
}

function check(name, aspect, prints) {
  const problems = [];

  /*
    RULE ONE IS CHECKED IN THREE DIRECTIONS, not one, because they are not
    alike.

    SIDEWAYS there is spare panel either side, and prints running off the
    edge is the effect the pile wants — so this is the generous one.

    UP there is the panel title, which on the gallery is WHITE, chosen for
    the dark plum ground. A print reaching into it does not merely cover
    it: the title paints on top (`.panel-head` carries a z-index above the
    pile) and then reads white-on-white, which looks like a rendering
    fault rather than a layout one. This is the strict direction.

    DOWN there is the scene object — white line art, same problem, but
    further away.

    The numbers come from the measured layout at 375x812, the tightest
    case: 15px of gap above the stage (3.3% of its height) and 31px below
    (6.9%). These sit just inside those.
  */
  const MAX_SPILL_X = 13;
  const MAX_SPILL_TOP = 3;
  const MAX_SPILL_BOTTOM = 6;
  prints.forEach((p, i) => {
    const { hw, hh } = halfExtents(p.w, aspect);
    const sx = Math.max(0, hw - p.x, p.x + hw - 100);
    const top = Math.max(0, hh - p.y);
    const bottom = Math.max(0, p.y + hh - 100);
    if (sx > MAX_SPILL_X) {
      problems.push(
        `RULE ONE  print ${i + 1} spills ${sx.toFixed(1)}% off the side (max ${MAX_SPILL_X})`,
      );
    }
    if (top > MAX_SPILL_TOP) {
      problems.push(
        `RULE ONE  print ${i + 1} reaches ${top.toFixed(1)}% above the stage, into the title (max ${MAX_SPILL_TOP})`,
      );
    }
    if (bottom > MAX_SPILL_BOTTOM) {
      problems.push(
        `RULE ONE  print ${i + 1} reaches ${bottom.toFixed(1)}% below the stage, into the object (max ${MAX_SPILL_BOTTOM})`,
      );
    }
  });

  /* Equal z is decided by DOM order — the later print paints on top — so
     those pairs are real stacking relationships, not ties to skip. */
  const above = (a, b) =>
    a.z > b.z || (a.z === b.z && prints.indexOf(a) > prints.indexOf(b));

  for (const a of prints) {
    for (const b of prints) {
      if (a === b) continue;
      if (!above(a, b)) continue;
      if (covers(a, b, aspect)) {
        problems.push(
          `RULE TWO  print ${prints.indexOf(b) + 1} (z${b.z}) centre is buried by print ${prints.indexOf(a) + 1} (z${a.z})`,
        );
      }
    }
  }

  const zs = new Set(prints.map((p) => p.z));
  const sizes = prints.map((p) => p.w);
  console.log(
    `\n${name}  —  ${prints.length} prints, aspect ${aspect.toFixed(3)}, ` +
      `widths ${Math.min(...sizes)}-${Math.max(...sizes)}%, ${zs.size} z-levels`,
  );
  if (problems.length === 0) {
    console.log("  PASS — every print fits and every centre is clickable");
  } else {
    problems.forEach((p) => console.log("  " + p));
  }
  return problems.length === 0;
}

export { check, halfExtents };

const layouts = (await import("./scatter-layout.mjs")).default;
let ok = true;
for (const l of layouts) ok = check(l.name, l.aspect, l.prints) && ok;
console.log(ok ? "\nAll layouts pass.\n" : "\nFIX THE ABOVE.\n");
process.exit(ok ? 0 : 1);
