#!/usr/bin/env python3
"""
Package the hand-authored pen paths for the component.

    python scripts/emit-strokes.py

Reads  scripts/strokes.json          (hand-authored — the actual drawing)
Writes src/components/deck/name-strokes.generated.ts

Only the PACKAGING is mechanical. The paths themselves are drawn by hand
against the letterform outlines; see scripts/preview-strokes.py for the
residue check and the filmstrip used to judge them.

What this adds on top of the JSON:

  * flattens `shapes` x `place` into concrete strokes, so 'a' and 'n' —
    each drawn once but used in both names — become four entries,
  * multiplies each stroke's within-glyph share by its glyph's weight to
    get its share of the whole LINE, and asserts those sum to 1,
  * accumulates `at`, the point in the line where each stroke starts.

`at` and `of` are what let the CSS give every stroke a duration
proportional to its length. Without them the pen crawls through short
strokes and races through long ones, which is the clearest tell of a fake
handwriting animation.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PEN = ROOT / "scripts" / "strokes.json"
OUT = ROOT / "src" / "components" / "deck" / "name-strokes.generated.ts"

HEADER = """/**
 * GENERATED by scripts/emit-strokes.py from scripts/strokes.json.
 * DO NOT EDIT BY HAND — edit scripts/strokes.json and re-run that script.
 *
 * The pen paths are hand-drawn; only this packaging is mechanical.
 *
 * `at` is where a stroke starts as a fraction of its line's total pen
 * travel, `of` is its share of it. They exist so each stroke's duration
 * can be proportional to its length, keeping one pen speed across the
 * whole word.
 *
 * Units match name-outlines.generated.ts: hundredths of an em, y-down,
 * line A's baseline at y=0.
 */

"""


def main() -> None:
    pen = json.loads(PEN.read_text(encoding="utf-8"))
    lines: dict[str, list] = {"a": [], "amp": [], "b": []}
    acc: dict[str, float] = {}

    for place in pen["place"]:
        weight = place.get("weight", 1.0)
        for shape in pen["shapes"][place["shape"]]:
            line = place["line"]
            share = shape["of"] * weight
            at = acc.get(line, 0.0)
            acc[line] = at + share
            lines[line].append({
                "glyph": place["glyph"],
                "d": shape["d"],
                "dx": place["dx"],
                "dy": place["dy"],
                "at": round(at, 6),
                "of": round(share, 6),
            })

    for line, total in acc.items():
        if abs(total - 1.0) > 1e-6:
            raise SystemExit(
                f"\n  ERROR: line {line!r} shares sum to {total}, not 1.\n"
                f"  Fix the `weight` values in scripts/strokes.json.\n")

    payload = {"width": pen["width"], "lines": lines}
    OUT.write_text(HEADER + f"export const nameStrokes = {json.dumps(payload, indent=2)} as const;\n",
                   encoding="utf-8")

    print(f"  wrote {OUT.relative_to(ROOT)}")
    for line, items in lines.items():
        print(f"    line {line}: {len(items)} strokes, shares sum to {acc[line]:.6f}")


if __name__ == "__main__":
    main()
