/*
 * SUPERSEDED — the gallery is a tiled collage now, not a scattered pile.
 *
 * Nothing in the shipping stylesheet comes from this file any more; the
 * layout is generated by gen-collage.mjs and verified by check-collage.mjs.
 * Kept because it is the rollback path: it is the only record of how the
 * scattered pile was built, and rebuilding that by hand would be a day's
 * work over eighteen positions.
 *
 * If the collage is here to stay, delete this, scatter-layout.mjs and
 * check-scatter.mjs together — they only make sense as a set.
 */
/*
 * Generates a print pile that does not look like a grid.
 *
 *     node scripts/gen-scatter.mjs            # emit CSS for both breakpoints
 *     node scripts/gen-scatter.mjs --seeds    # score a range of seeds
 *
 * WHY GENERATED AND NOT HAND-PLACED. The hand-placed version was a 6x3 and
 * a 4x5 grid with a couple of percent of jitter, and it read as exactly
 * that: a rectangle of photographs. Eighteen positions is too many to
 * scatter convincingly by eye, and the constraint that makes a pile work is
 * not aesthetic — it is that no photograph may become unopenable.
 *
 * THREE THINGS MAKE IT READ AS TOSSED RATHER THAN ARRANGED:
 *
 *   1. BEST-CANDIDATE SAMPLING (Mitchell). Each print is placed by drawing
 *      several candidate positions and keeping whichever sits furthest from
 *      everything already down. That yields blue noise — evenly spread but
 *      with no lattice — which is what a scattered pile actually is. Pure
 *      uniform random would clump and leave holes; a grid has neither.
 *
 *   2. A LUMPY REGION, NOT A RECTANGLE. Centres are drawn from an ellipse
 *      whose radius wobbles with angle, so the pile's silhouette is
 *      irregular. This is what stops the outline reading as a box.
 *
 *   3. WIDE VARIATION in size and angle, with rotations pushed away from
 *      zero so no print looks accidentally square to the frame.
 *
 * RULE TWO IS ENFORCED DURING PLACEMENT, not checked afterwards. Prints are
 * laid down in ascending z, so each new one covers everything before it: a
 * candidate is rejected if it would sit over an existing print's centre, or
 * if its own centre falls under the hero. That makes a bad pile impossible
 * to generate rather than merely unlikely.
 *
 * The seed is fixed, so the output is stable — re-running gives the same
 * pile, and the numbers can be committed like any other design decision.
 */

import { pathToFileURL } from "node:url";

const TALL = 1.08; // a print is this much taller than it is wide

/* Deterministic PRNG — the same pile every run. */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* Does `box` cover `pt`? Both in stage %, x against width and y against
   height, so the rotation is done in a square space and mapped back. */
function covers(box, pt, aspect) {
  const hw = box.w / 2;
  const hh = (TALL * box.w * aspect) / 2;
  const rad = (-box.rot * Math.PI) / 180;
  const dx = pt.x - box.x;
  const dy = (pt.y - box.y) / aspect;
  const lx = dx * Math.cos(rad) - dy * Math.sin(rad);
  const ly = dx * Math.sin(rad) + dy * Math.cos(rad);
  return Math.abs(lx) < hw && Math.abs(ly * aspect) < hh;
}

/*
  How far a print hangs outside the stage, in % of stage width and height.

  THE REGION ONLY BOUNDS CENTRES, which is not the same thing at all: a
  centre 1% from the left edge puts half a print outside it. Unbounded, the
  generator produced a print whose centre sat at y 98.5% — hanging 18.7%
  below the stage, straight through the chair and its caption.

  THREE LIMITS, NOT TWO, because up and down are not alike either.

  Sideways there is spare panel and prints running off the edge is the
  effect the pile wants. UP there is the panel title, which on this panel
  is WHITE — chosen for the dark plum ground. A print reaching into it does
  not merely cover it: the title paints on top (see the z-index on
  `.panel-head`) and then reads white-on-white, which is worse than being
  hidden because it looks like a rendering fault. DOWN there is the scene
  object, white line art with the same problem.

  So the budgets are measured from the layout rather than guessed. At
  375x812 the gap between the title and the stage is 15px — 3.3% of the
  stage — and between the stage and the object 31px, or 6.9%. The limits
  below sit just inside those.
*/
function spill(q, aspect) {
  const hw = q.w / 2;
  const hh = (TALL * q.w * aspect) / 2;
  return {
    x: Math.max(0, hw - q.x, q.x + hw - 100),
    top: Math.max(0, hh - q.y),
    bottom: Math.max(0, q.y + hh - 100),
  };
}

/* The lumpy region centres are drawn from. Two low harmonics on the radius
   give an outline that is clearly not an ellipse and clearly not a box. */
function inRegion(x, y, cfg, phase) {
  const nx = (x - 50) / cfg.rx;
  const ny = (y - 50) / cfg.ry;
  const th = Math.atan2(ny, nx);
  const wobble =
    1 + 0.18 * Math.sin(3 * th + phase[0]) + 0.11 * Math.sin(5 * th + phase[1]);
  return Math.hypot(nx, ny) <= wobble;
}

function build(cfg, seed) {
  const rand = rng(seed);
  const phase = [rand() * 6.283, rand() * 6.283];
  const { aspect } = cfg;

  /* Distance in a common unit, so "furthest from everything" means the same
     thing horizontally and vertically on a non-square stage. */
  const dist = (a, b) => Math.hypot(a.x - b.x, (a.y - b.y) / aspect);

  const pick = (lo, hi) => lo + rand() * (hi - lo);
  /*
    Rotation, pushed away from 0 so nothing sits square to the frame.

    THE SIGNS ARE DEALT FROM A BALANCED DECK, not flipped per print. A coin
    flip per print is what randomness actually looks like, and on eighteen
    prints it came out 14 leaning one way and 4 the other — a pile that all
    leans left reads as a deliberate fan, not a scatter. Half the prints
    turn each way, shuffled.
  */
  const signs = Array.from({ length: cfg.count }, (_, i) => (i % 2 ? 1 : -1));
  for (let i = signs.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [signs[i], signs[j]] = [signs[j], signs[i]];
  }
  let signAt = 0;
  const angle = () => +(pick(cfg.rotMin, cfg.rotMax) * signs[signAt++ % signs.length]).toFixed(1);

  /* The hero is not sampled against candidates — it is placed first, near
     the middle, as the obstacle everything else is arranged around. Its
     jitter is small enough that it cannot reach an edge. */
  const hero = {
    x: +pick(50 - cfg.heroJit, 50 + cfg.heroJit).toFixed(1),
    y: +pick(50 - cfg.heroJit, 50 + cfg.heroJit).toFixed(1),
    w: cfg.heroW,
    rot: angle(),
    hero: true,
  };

  const placed = [];
  for (let i = 0; i < cfg.count - 1; i++) {
    let best = null;
    let bestScore = -1;
    for (let t = 0; t < cfg.candidates; t++) {
      const cand = {
        x: +pick(0, 100).toFixed(1),
        y: +pick(0, 100).toFixed(1),
        w: +pick(cfg.wMin, cfg.wMax).toFixed(0),
        rot: angle(),
      };
      if (!inRegion(cand.x, cand.y, cfg, phase)) continue;
      const sp = spill(cand, aspect);
      if (sp.x > cfg.maxSpillX) continue;
      if (sp.top > cfg.maxSpillTop || sp.bottom > cfg.maxSpillBottom) continue;
      /* Its own centre must not be under the hero, which sits on top. */
      if (covers(hero, cand, aspect)) continue;
      /* It is going above everything already placed, so it must not cover
         any of their centres. */
      if (placed.some((q) => covers(cand, q, aspect))) continue;
      /* And nothing already placed may swallow this one's centre either —
         only matters for equal-z ties, but keeps the pile honest. */
      const score = placed.length
        ? Math.min(...placed.map((q) => dist(cand, q)))
        : 1e9;
      if (score > bestScore) {
        bestScore = score;
        best = cand;
      }
    }
    if (!best) return null; // this seed cannot fit them all
    placed.push(best);
  }

  /* z = placement order; the hero takes the top. */
  const prints = placed.map((q, i) => ({ ...q, z: i + 3 }));
  return [{ ...hero, z: prints.length + 5 }, ...prints];
}

/* How grid-like is it? Distinct x and y values relative to the count — a
   lattice reuses a handful of coordinates, a scatter reuses none. */
function score(prints, aspect) {
  const cluster = (vals) => {
    const s = [...vals].sort((a, b) => a - b);
    let n = 1;
    for (let i = 1; i < s.length; i++) if (s[i] - s[i - 1] > 3) n++;
    return n;
  };
  const xs = cluster(prints.map((p) => p.x));
  const ys = cluster(prints.map((p) => p.y));
  const dists = [];
  for (const a of prints) {
    const d = prints
      .filter((b) => b !== a)
      .map((b) => Math.hypot(a.x - b.x, (a.y - b.y) / aspect));
    dists.push(Math.min(...d));
  }
  const mean = dists.reduce((s, v) => s + v, 0) / dists.length;
  const spread = Math.min(...dists);
  return { xs, ys, minGap: +spread.toFixed(1), meanGap: +mean.toFixed(1) };
}

const WIDE = {
  name: "wide",
  aspect: 16 / 9,
  count: 18,
  wMin: 21,
  wMax: 29,
  heroW: 33,
  heroJit: 7,
  rotMin: 4,
  rotMax: 15,
  rx: 56,
  ry: 46,
  maxSpillX: 13,
  maxSpillTop: 3,
  maxSpillBottom: 6,
  candidates: 1400,
};

const PHONE = {
  name: "phone",
  aspect: 3 / 4,
  count: 18,
  wMin: 33,
  wMax: 45,
  heroW: 52,
  heroJit: 8,
  rotMin: 4,
  rotMax: 15,
  rx: 50,
  ry: 52,
  maxSpillX: 11,
  maxSpillTop: 3,
  maxSpillBottom: 6,
  candidates: 1400,
};

function emit(cfg, prints, indent) {
  const lines = prints.map(
    (q, i) =>
      `${indent}.prints > li:nth-child(${i + 1})${i + 1 > 9 ? "" : " "} ` +
      `{ --x: ${q.x}%; --y: ${q.y}%; --w: ${q.w}%; --rot: ${q.rot}deg; --z: ${q.z}; }`,
  );
  return lines.join("\n");
}

export { build, score, WIDE, PHONE };

/* CLI only. Guarded, or importing this module to reuse `build` runs the
   whole script and calls process.exit() out from under the caller. */
const isCli = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
const args = isCli ? process.argv.slice(2) : [];
if (isCli) {

if (args.includes("--seeds")) {
  for (const cfg of [WIDE, PHONE]) {
    console.log(`\n${cfg.name}:`);
    for (let seed = 1; seed <= 40; seed++) {
      const prints = build(cfg, seed);
      if (!prints) continue;
      const s = score(prints, cfg.aspect);
      console.log(
        `  seed ${String(seed).padStart(2)}  distinct x ${String(s.xs).padStart(2)}/18  ` +
          `y ${String(s.ys).padStart(2)}/18  min gap ${String(s.minGap).padStart(4)}  mean ${s.meanGap}`,
      );
    }
  }
} else {
  const seeds = { wide: Number(args[0] ?? 7), phone: Number(args[1] ?? 7) };
  for (const cfg of [PHONE, WIDE]) {
    const prints = build(cfg, seeds[cfg.name]);
    if (!prints) throw new Error(`seed ${seeds[cfg.name]} failed for ${cfg.name}`);
    console.log(`/* ${cfg.name} — seed ${seeds[cfg.name]} */`);
    console.log(emit(cfg, prints, cfg.name === "wide" ? "  " : ""));
    console.log("//", JSON.stringify(score(prints, cfg.aspect)));
  }
}
}
