/*
 * SUPERSEDED — the gallery is a tiled collage now, not a scattered pile.
 *
 * Nothing in the shipping stylesheet comes from this file any more; the
 * layout is generated by gen-collage.mjs and verified by check-collage.mjs.
 * Kept because it is the rollback path: it is the only record of how the
 * scattered pile was built, and rebuilding that by hand would be a day's
 * work over eighteen positions.
 *
 * If the collage is here to stay, delete this, scatter-layout.mjs and
 * check-scatter.mjs together — they only make sense as a set.
 */
/*
 * The print-pile layouts, in the form scripts/check-scatter.js verifies.
 * Keep these in step with `.prints > li:nth-child(n)` in globals.css —
 * this file is the working copy the geometry is checked in.
 *
 * p(x, y, w, rot, z)
 */
const p = (x, y, w, rot, z) => ({ x, y, w, rot, z });

/* ── What shipped before: 12 prints. Kept so the checker can be re-proved
      against a layout already known good. ── */
const OLD_PHONE = [
  p(50, 39, 44, -3, 12), p(21, 17, 34, -9, 3), p(50, 17, 32, 6, 4),
  p(79, 17, 34, -6, 5), p(21, 39, 34, 7, 6), p(79, 39, 34, -8, 6),
  p(21, 61, 34, -5, 5), p(50, 61, 32, 8, 7), p(79, 61, 34, 5, 5),
  p(21, 83, 34, 6, 4), p(50, 83, 32, -7, 3), p(79, 83, 34, 4, 4),
];
const OLD_WIDE = [
  p(46, 50, 32, -3, 12), p(15, 24, 24, -9, 3), p(38, 23, 23, 6, 4),
  p(62, 24, 24, -6, 5), p(85, 26, 23, 8, 3), p(14, 50, 25, 5, 6),
  p(70, 50, 24, -7, 7), p(88, 52, 22, 4, 3), p(15, 76, 24, 7, 4),
  p(38, 77, 23, -5, 5), p(62, 76, 24, 4, 3), p(85, 74, 23, -8, 4),
];

/*
 * ── NEW: 18 prints, SCATTERED ──
 *
 * These are not typed by hand any more. They come from
 * scripts/gen-scatter.mjs — blue-noise placement in a lumpy, non-
 * rectangular region — and are pasted here so this file stays the thing
 * the checker verifies. Regenerate with:
 *
 *     node scripts/gen-scatter.mjs 43 2     # wide seed, phone seed
 *
 * THE CHECKER IS A SECOND, INDEPENDENT IMPLEMENTATION of the two rules.
 * The generator enforces them while placing; the checker re-proves them
 * afterwards from the emitted numbers, and it still re-proves the OLD
 * twelve-print layout as well. Two implementations agreeing is the whole
 * point — either one of them could be wrong, and the vertical-spill limit
 * is a case where they disagreed and the checker was right.
 *
 */
const PHONE = [
  p(42.6, 56.6, 52, -4.7, 22),
  p(12.8, 19.2, 33, 14.3, 3),
  p(84.9, 90.8, 33, 11.8, 4),
  p(92.3, 31, 34, 14.7, 5),
  p(6.3, 77.6, 34, -10.9, 6),
  p(71.9, 59.7, 43, 12, 7),
  p(55.7, 15.7, 35, -7, 8),
  p(45.8, 82.7, 40, -7.6, 9),
  p(9.3, 48.5, 34, -12.7, 10),
  p(36.4, 33.3, 36, 6.6, 11),
  p(82.3, 11, 33, 4.8, 12),
  p(68, 41.6, 38, -4.8, 13),
  p(86.6, 73, 35, -10.9, 14),
  p(64.9, 78.6, 34, -10.6, 15),
  p(92.7, 48.9, 36, -11.6, 16),
  p(25.3, 80.3, 37, -6, 17),
  p(35.2, 16.6, 37, -5.6, 18),
  p(73.8, 25.4, 36, 6.9, 19),
];

const WIDE = [
  p(56.1, 46.3, 33, -4.6, 22),
  p(93.5, 38.8, 26, 8.7, 3),
  p(0.4, 84.8, 22, -12.3, 4),
  p(34, 19.1, 23, -7, 5),
  p(59.5, 80.9, 26, -10.2, 6),
  p(29.5, 76.6, 28, 14.1, 7),
  p(5.4, 30.9, 26, -8.2, 8),
  p(88.2, 81.9, 23, -10.4, 9),
  p(72, 24.9, 28, -13.7, 10),
  p(75.5, 57.8, 22, -6.2, 11),
  p(23.4, 45.8, 22, 7.1, 12),
  p(39.3, 50.5, 23, 6.2, 13),
  p(8.9, 59.4, 25, 5.4, 14),
  p(19.4, 17.5, 21, -7.6, 15),
  p(15.5, 83.1, 22, -12.7, 16),
  p(44.1, 79.8, 24, -13.6, 17),
  p(97.6, 62, 21, -14.8, 18),
  p(71.6, 79.9, 23, 8.4, 19),
];

const LAYOUTS = [
  { name: "OLD phone (3/4), 12", aspect: 3 / 4, prints: OLD_PHONE },
  { name: "OLD wide (4/3), 12", aspect: 4 / 3, prints: OLD_WIDE },
  { name: "NEW phone (3/4), 18", aspect: 3 / 4, prints: PHONE },
  { name: "NEW wide (16/9), 18", aspect: 16 / 9, prints: WIDE },
];

export default LAYOUTS;
